openapi: 3.1.0
x-stoplight:
  id: nrvetril0yhal
info:
  title: ev.energy v2 API
  version: '2.0'
  contact:
    email: developers@ev.energy
    url: developers.ev.energy
    name: Philip Douglas
  description: 'The official API for ev.energy, version 2.'
  license:
    name: Proprietary
    url: 'https://ev.energy'
  termsOfService: ''
servers:
  - url: 'https://api.ev.energy/v2'
    description: Live API for both production and sandbox requests.
    x-internal: false
  - description: Staging server for internal testing only.
    url: 'https://api-staging.ev.energy/v2'
    x-internal: true
paths:
  /:
    get:
      summary: API root
      description: Get links to resources accessible in the API.
      operationId: get-root
      security: []
      tags:
        - Root
      x-stoplight:
        id: m467m8cgddnw0
  /users:
    get:
      summary: List users
      tags:
        - Users
      operationId: get-users
      x-stoplight:
        id: mlewj44bxydta
      description: List all the users that the authorization token has access to.
      security:
        - oauth2:
            - 'user:read'
  '/users/{user_id}':
    get:
      summary: Retrieve user
      description: 'Retrieve information about a single, specific user.'
      tags:
        - Users
      operationId: get-users-user_id
      x-stoplight:
        id: hg9ev9nrzxnqe
      security:
        - oauth2:
            - 'user:read'
  /evses:
    get:
      summary: List EVSEs
      tags:
        - EVSEs
      operationId: get-evses
      x-stoplight:
        id: x0q19vlrqdbcx
      description: List all the EVSEs that the authorization token has access to.
      security:
        - oauth2:
            - 'evse:read'
  '/evses/{evse_id}':
    get:
      summary: Retrieve an EVSE
      tags:
        - EVSEs
      operationId: get-evses-evse_id
      x-stoplight:
        id: 7zm917wj8m6m7
      description: 'Retrive a single, specific EVSE''s details.'
      security:
        - oauth2:
            - 'evse:read'
  /evse_models:
    get:
      summary: List EVSE models
      tags:
        - EVSEs
      operationId: get-evse_models
      x-stoplight:
        id: 19fs08z8m1v9o
      description: List all the EVSE models known by the ev.energy system.
      security:
        - oauth2:
            - 'evse:read'
  '/evse_models/{evse_model_id}':
    get:
      summary: Retrieve an EVSE model
      tags:
        - EVSEs
      operationId: get-evse_models-evse_model_id
      x-stoplight:
        id: nb7b19hk7ey6w
      description: 'Retrieve details for a single, specific EVSE model.'
      security:
        - oauth2:
            - 'evse:read'
  /evse_makes:
    get:
      summary: List EVSE makes
      tags:
        - EVSEs
      operationId: get-evse_makes
      x-stoplight:
        id: 9y3oaz1ifkvop
      description: List all the EVSE makes known by the ev.energy system.
      security:
        - oauth2:
            - 'evse:read'
  '/evse_makes/{evse_make_id}':
    get:
      summary: Retrieve an EVSE make
      tags:
        - EVSEs
      operationId: get-evse_makes-evse_make_id
      x-stoplight:
        id: dxqoxuhfydk9m
      description: 'Retrieve details for a single, specific EVSE make.'
      security:
        - oauth2:
            - 'evse:read'
  '/evses/{evse_id}/status_logs':
    get:
      summary: List status logs for an EVSE
      description: List the historical status logs for a specific EVSE. Used to find out the state of the EVSE at each point it reported in to ev.energy.
      tags:
        - EVSEs
      operationId: get-evses-evse_id-status_logs
      x-stoplight:
        id: p83ql1le16pk0
      security:
        - oauth2:
            - 'evse:read'
  '/evses/{evse_id}/status_logs/{sampled_at}':
    get:
      summary: Retrieve a status log for an EVSE
      description: An EVSE status log is uniquely identified by the combination of EVSE ID and the time it was sampled at.
      tags:
        - EVSEs
      operationId: get-evses-evse_id-status_logs-timestamp
      x-stoplight:
        id: 8v0qmuuuwvo1a
      security:
        - oauth2:
            - 'evse:read'
  /vehicles:
    get:
      summary: List vehicles
      tags:
        - Vehicles
      operationId: get-vehicles
      x-stoplight:
        id: byq7mfhb4trl8
      description: List all the vehicles that the authorization token has access to.
      security:
        - oauth2:
            - 'vehicle:read'
  '/vehicles/{vehicle_id}':
    get:
      summary: Retrieve a vehicle
      tags:
        - Vehicles
      operationId: get-vehicles-vehicle_id
      x-stoplight:
        id: mx82m7fdz7mew
      description: 'Retrive a single, specific vehicle''s details.'
      security:
        - oauth2:
            - 'vehicle:read'
  /vehicle_trims:
    get:
      summary: List vehicle trims
      tags:
        - Vehicles
      operationId: get-vehicle_trims
      x-stoplight:
        id: k1a53amf7giw0
      description: |-
        List all the vehicle trims known by the ev.energy system.

        Trim refers to a set of features that can be applied to a particular model of vehicle: https://en.wikipedia.org/wiki/Car_model#Trim_level.
      security:
        - oauth2:
            - 'vehicle:read'
  '/vehicle_trims/{vehicle_trim_id}':
    get:
      summary: Retrieve a vehicle trim
      tags:
        - Vehicles
      operationId: get-vehicle_trims-vehicle_trim_id
      x-stoplight:
        id: bs9ijzxrktt4h
      description: |-
        Retrieve details for a single, specific vehicle trim.

        Trim refers to a set of features that can be applied to a particular model of vehicle: https://en.wikipedia.org/wiki/Car_model#Trim_level.
      security:
        - oauth2:
            - 'vehicle:read'
  /vehicle_models:
    get:
      summary: List vehicle models
      tags:
        - Vehicles
      operationId: get-vehicle_models
      x-stoplight:
        id: nyxgg2lz8n4gx
      description: List all the vehicle models known by the ev.energy system.
      security:
        - oauth2:
            - 'vehicle:read'
  '/vehicle_models/{vehicle_model_id}':
    get:
      summary: Retrieve a vehicle model
      tags:
        - Vehicles
      operationId: get-vehicle_models-vehicle_model_id
      x-stoplight:
        id: 2fq8ir4i5w4bn
      description: 'Retrieve details for a single, specific vehicle model.'
      security:
        - oauth2:
            - 'vehicle:read'
  /vehicle_makes:
    get:
      summary: List vehicle makes
      tags:
        - Vehicles
      operationId: get-vehicle_makes
      x-stoplight:
        id: wn0iisxnkd8pb
      description: List all the vehicle makes known by the ev.energy system.
      security:
        - oauth2:
            - 'vehicle:read'
  '/vehicle_makes/{vehicle_make_id}':
    get:
      summary: Retrieve a vehicle make
      description: 'Retrieve details for a single, specific vehicle make.'
      tags:
        - Vehicles
      operationId: get-vehicle_makes-vehicle_make_id
      x-stoplight:
        id: hpezq6afvgn6w
      security:
        - oauth2:
            - 'vehicle:read'
  '/vehicles/{vehicle_id}/status_logs':
    get:
      summary: List status logs for a vehicle
      description: List the historical status logs for a specific Vehicle. Used to find out the state of the Vehicle at each point it reported in to ev.energy.
      tags:
        - Vehicles
      operationId: get-vehicles-vehicle_id-status_logs
      x-stoplight:
        id: d2a6w8ubmvmhs
      security:
        - oauth2:
            - 'vehicle:read'
  '/vehicles/{vehicle_id}/status_logs/{logged_at}':
    get:
      summary: Retrieve a specific status log for a vehicle
      description: A single status log for a particular vehicle is uniquely identified by the timestamp it was logged at.
      tags:
        - Vehicles
      operationId: get-vehicles-vehicle_id-status_logs-timestamp
      x-stoplight:
        id: zq7wdbphcaih2
      security:
        - oauth2:
            - 'vehicle:read'
  /suppliers:
    get:
      summary: 'List suppliers, sorted alphabetically by name.'
      tags:
        - Tariffs
      operationId: get-suppliers
      x-stoplight:
        id: 5oqluc195ncyw
      description: |-
        List all the energy suppliers known by the ev.energy system.

        Use the `available_for_user_id` query parameter to narrow the list to only those relevant to a specific user.
      security:
        - oauth2:
            - 'tariff:read'
  '/suppliers/{supplier_id}':
    get:
      summary: Retrieve a supplier
      tags:
        - Tariffs
      operationId: get-suppliers-suppler_id
      x-stoplight:
        id: ae7ofq6ulc00a
      description: 'Retrieve details for a single, specific energy supplier.'
      security:
        - oauth2:
            - 'tariff:read'
  /tariffs:
    get:
      summary: 'List tariffs, sorted alphabetically by name.'
      tags:
        - Tariffs
      operationId: get-tariffs
      x-stoplight:
        id: fn3qhgdz0xbgp
      description: |-
        List all the energy supplier tariffs known by the ev.energy system.

        Use the `available_for_user_id` query parameter to narrow the list to only those relevant to a specific user and `supplier` query parameter to list only tariffs for a specific supplier.
      security:
        - oauth2:
            - 'tariff:read'
  '/tariffs/{tariff_id}':
    get:
      summary: Retrieve a tariff
      tags:
        - Tariffs
      operationId: get-tariffs-tariff_id
      x-stoplight:
        id: iy86jtq2k83i6
      description: 'Retrieve details for a single, specific tariff.'
      security:
        - oauth2:
            - 'tariff:read'
  /charging_sub_sessions:
    get:
      summary: List charging sub sessions
      description: List all charging sub sessions visible to the authenticated client.
      tags:
        - Charging Sessions
      operationId: get-charging_sub_sessions
      x-stoplight:
        id: ndz0izsn6bvif
      security:
        - oauth2:
            - 'charging_session:read'
  '/charging_sub_sessions/{charging_sub_session_id}':
    get:
      summary: Retrieve a charging sub-session
      description: 'Retrieve a specific charging sub-session, representing a period of charging in a single mode.'
      tags:
        - Charging Sessions
      operationId: get-charging_sub_sessions-charging_sub_session_id
      x-stoplight:
        id: tjkana9omjrlm
      security:
        - oauth2:
            - 'charging_session:read'
  /notifications:
    get:
      summary: List notifications
      tags:
        - Notifications
      operationId: get-notifications
      x-stoplight:
        id: qxlylwdb3307s
      description: |-
        Lists notifications for the user making the request. For each
        notification it returns a category (INFO, ERROR etc) and a title
        (in the user's language) for display in their inbox.
  '/notifications/{notification_id}':
    get:
      summary: Retrieve a notification
      tags:
        - Notifications
      operationId: get-notifications-notification_id
      x-stoplight:
        id: uxw0bvrq29itl
      description: |-
        Retrieves the full details of a specified notification. The title,
        short_text and long_text fields will be translated into the user's
        language.
      security:
        - oauth2: []
  /webhook_portal:
    get:
      summary: Retrieve access link for webhook portal
      tags:
        - Webhooks
      operationId: get-webhook_portal
      x-stoplight:
        id: 67qh66tybc8mn
      description: Generate a one time use link to access the portal to configure webhooks.
      security:
        - oauth2: []
webhooks:
  charging_sub_session.created:
    post:
      summary: Charging sub-session created
      description: 'A charging sub-session is created, representing a period of charging in a single mode.'
      tags:
        - Charging Sessions
  charging_sub_session.ended:
    post:
      summary: Charging sub-session ended
      description: 'A charging sub-session has ended, representing a period of charging in a single mode.'
      tags:
        - Charging Sessions
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://api.ev.energy/o/token/'
          refreshUrl: 'https://api.ev.energy/o/token/'
          scopes:
            'evse:read': ''
            'vehicle:read': ''
            'user:read': ''
            'charging_session:read': ''
            'tariff:read': ''
        authorizationCode:
          authorizationUrl: 'https://api.ev.energy/o/authorize/'
          tokenUrl: 'https://api.ev.energy/o/token/'
          refreshUrl: 'https://api.ev.energy/o/token/'
          scopes: {}
x-internal: false
security:
  - oauth2: []
tags:
  - name: Charging Sessions
    description: Endpoints related to records of charging.
  - name: CSV
    description: Endpoints that return CSV responses only and are not linkable to other endpoint data.
  - name: EVSEs
    description: Endpoints for interacting with EVSEs.
  - name: Notifications
    description: Endpoints for communicating notifications.
  - name: Root
    description: The root endpoint which lists all the top-level collections.
  - name: Tariffs
    description: Endpoints related to energy suppliers and their tariffs.
  - name: Users
    description: Endpoints for interacting with users.
  - name: Vehicles
    description: Endpoints for interacting with vehicles.
  - name: Webhooks
    description: Endpoints for configuring and managing webhooks.
